#关闭熔断
feign:
  hystrix:
    enabled: false
spring:
  jpa:
    show-sql: false
    #spring-cloud 配置无效
  session:
      store-type: redis
  redis:
    host: 47.92.82.130
    port: 9736
    password:
    database: 0
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.82.130:3306/db_user_test?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: zxapp@2709
    filters: stat
    max-active: 10
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

  application:
      name: service-user

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.pq.user.entity

user:
  secret_key: $1$JHhjNnOd
captcha:
  service:
    maxFailedCount: 100
    maxSendCountOfDay: 100
    isBlockSendSMS: false
    captchaTimeOut: 300000
    sendCaptchaIntervalTime: 60000
    coolDown: 60

# redis password
redis:
  reset_password_token:
    expire: 300
  password_error_log:
    expire: 10800
    max_number: 5
#sql 日志打印  root（项目）日志打印级别
logging:
  level:
#    root: warn
    com:
      pq:
        user:
          mapper: debug
  config:
    classpath: logback-spring.xml

pq:
  log-path: /Users/liutao/data/logs/pq-user-service

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://182.92.106.98:12128/
### xxl-job executor address
    executor:
      appName: xxl-job-coupon
      ip: 47.93.114.117
      port: 12029
### xxl-job log path
      logPath: /data/logs/jedi-job/jobhandler
### xxl-job log retention days
      logRetentionDays: -1
### xxl-job, access token
    accessToken:

#注册服务配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:9001/eureka/
server:
  port: 8085

php:
  url: http://47.92.82.130/sms/index.php/home/Demo/

#禁用注册服务
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
